### ISSUE TITLE
Send information of the device when Firebase token is registered

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-notification-service#32]
See https://github.com/gnosis/safe/issues/153

## Story
As a developer of the notification service, I would like to have more information of the devices registered in the service.

## Background
- Currently just the `firebase token` and the `ethereum address` is stored for every device
- It would be very useful for new functionalities to store information about the device (operating system, version, client), so we can use different logic for every device depending on `iOs`, `Android`, `Web`...

## Acceptance criteria
* The following information are required by the new endpoint:
  - Array of signatures `(r, s, v)` that where generated by the accounts that should be registered
  - Firebase push token
  - Build number (e.g. `1644`)
  - Version name (e.g. `1.0.0`)
  - Client (e.g. `android`, `ios` or `extension`) 
  - Bundle identifier (e.g. `io.gnosis.safe` or `pm.gnosis.heimdall`)

The payload should be in the following format:
```json
{
  "push_token": "<string>",
  "build_number": "<integer>",
  "version_name": "<string>",
  "client": "[android | ios | extension]",
  "bundle": "<string>",
  "signatures": [
    {
      "v": "<integer>",
      "r": "<stringified int>", 
      "s": "<stringified int>"
    },
  ]
}
```

Each signature is generated by signing the following data:
`sha3("GNO" + <pushToken> + <build_number> + <version_name> + <client> + <bundle>)`

**Comment by rmeissner** [comment]
@Uxio0 @DmitryBespalov I would propose that the clients send the following info:

`client` -> `android`, `ios` or `extension` for now
`version` -> an integer indicating the version (e.g. 1677 would be the current version of android)

What about `language`, as the current device language (2 letter iso code) . This would allow us to send proper localisations for server triggered pushes.

Do we want to send something like the bundle identifier too? (e.g. `pm.gnosis.heimdall` on android ... not sure if this is really useful)

Did I miss anything?

**Comment by rmeissner** [comment]
also @Uxio0 I would maybe say to create a new endpoint so that we can make the parameters required, what do you think?

**Comment by Uxio0** [comment]
I think that should be enough for now. I would add `language` for sure, it might be useful at some point. The bundle identifier shouldn't be necessary

**Comment by Uxio0** [comment]
> also @Uxio0 I would maybe say to create a new endpoint so that we can make the parameters required, what do you think?

Yes, I was thinking on versioning the endpoint and deprecating the old one when everyone is updated

**Comment by rmeissner** [comment]
Ok I would then add the following to the specification:

- `language` - 2 letter iso code (for android we will put this into the translations and pull it from there ... android and languages is a joke)
- This informations should be updated on each client start, to avoid potential problems (alternative, we only update on changes and allow an explicit update)

WDYT @Uxio0 @DmitryBespalov @germartinez @germartinez

**Comment by germartinez** [comment]
I would find useful to allow the update of some owners at the same time because we will have different owners on each client with the same device data (version, language...)

**Comment by rmeissner** [comment]
So basically it would be an array of ethereum addresses, right?

**Comment by Uxio0** [comment]
> So basically it would be an array of ethereum addresses, right?

@germartinez @rmeissner If we are doing an endpoint similar to the one we are using now, we would have an array of `signatures`, as the `push_token` is signed using the `owner` private key and then `ecrecover` is used on the backend to get the `ethereum address`

**Comment by DmitryBespalov** [comment]
@rmeissner I would change `version` to be the marketing version string like we show in the menu. For example, `1.1.0 (2)`.

**Comment by DmitryBespalov** [comment]
+1 for bundle identifier and language

**Comment by rmeissner** [comment]
> I would change version to be the marketing version string like we show in the menu. For example, 1.1.0 (2).

any specific reason?

integer version numbers (or buildnumber, or whatever we want to call it) are very easy to compare and are a lot more detailed

**Comment by rmeissner** [comment]
also for the bundle identifier, do you have any use case? I couldn't come up with one, except maybe if we want to target different apps with our notification service 🤔

**Comment by germartinez** [comment]
The extension only uses the marketing version

**Comment by DmitryBespalov** [comment]
The string version number is more robust, and it can be converted from string to integer by the database (i suppose).

**Comment by DmitryBespalov** [comment]
for bundle identifier... yes, what if some other app is using our api and we want to see this, or new app comes up in our company and we want to separate it.. i think it is low overhead but the data is going to be there already

**Comment by rmeissner** [comment]
> The string version number is more robust

I disagree here

**Comment by Uxio0** [comment]
> Buildnumber is a integer set by the build environment, while a version string is set by anyone who creates a release. Therefore we now that buildnumbers are always increasing (also enforced by google for android) while a version string could go back to a previous version.

I agree with this. String version need to be set up manually, so from my point of view, more prone to errors. Clients might send both but I see it very redundant.
