### ISSUE TITLE
When addresses for push tokens are synced remove old addresses

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-notification-service#53]
Currently when using the new endpoint (v2/auth) to sync the push token to the service we are just adding the new tokens to the database (and if required update the known ones).

I would propose that we change the behaviour to remove all addresses (for the specified push token) that had not been send to the service, this will allow us to remove addresses that are not used anymore (e.g. Safe was removed on the device)

@germartinez would that work with the current extension implementation
@DmitryBespalov anything that would speak against this from iOS side

Reference: 
* https://github.com/gnosis/safe-notification-service/blob/master/safe_notification_service/safe/services/auth_service.py#L44

**Comment by rmeissner** [comment]
hmm this would not work with the current safe extension, so we would need adjustments, as there are some places were we only sync a single account (e.g. after creating a new account and when "resyncing")

**Comment by germartinez** [comment]
I agree with this. This way we are preventing all the possible communications that there may be with a removed Safe.
For the extension those changes should be implemented.

**Comment by DmitryBespalov** [comment]
I think it's fine. The service should overwrite existing registered data with a new one (push_token - [device owner]).

**Comment by Uxio0** [comment]
Just one concern. This feature will allow any user to delete another user push token if known. Push token should be private, but just as a check, @DmitryBespalov @rmeissner @germartinez are we exposing somehow the firebase tokens so a user could know another user's token?

**Comment by rmeissner** [comment]
we do not expose them on Android

**Comment by Uxio0** [comment]
@DmitryBespalov @germartinez What about iOs and the extension?

**Comment by germartinez** [comment]
@Uxio0 The extension does not expose them to the user, but Malory could intercept the communications with the service.

**Comment by Uxio0** [comment]
@germartinez Malory could do that if the service didn't run on https :wink:

**Comment by DmitryBespalov** [comment]
we do not expose them to the user @Uxio0

**Comment by Uxio0** [comment]
@germartinez @DmitryBespalov @rmeissner The fix is ready. I think the only one that has to implement changes is the extension, so let me know when you are ready so I deploy it in production
