### ISSUE TITLE
Potential webhook for WalletConnect on iOS

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-notification-service#56]
_This is a placeholder in case the iOS team realizes during implementation that we need it._
It might be necessary that we have a web hook to make push notifications work with WalletConnect on iOS.

### Why?
To enable a WalletConnect bridge to send push notifications to a device managed by us we need to provide a webhook.

### Notes
- We should NOT hand out push tokens

### Docs
https://docs.walletconnect.org/tech-spec#push-notifications
https://docs.walletconnect.org/push-server

**Comment by Uxio0** [comment]
@DmitryBespalov provided some info, but he said it doesn't need to be for this milestone. I can do it either way 

Relevant docs:
https://docs.walletconnect.org/tech-spec#push-notifications
https://docs.walletconnect.org/push-server
